//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMPresentation.App_Start {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CRMSys_Base {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CRMSys_Base() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CRMPresentation.App_Start.CRMSys_Base", typeof(CRMSys_Base).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a E-mail invalido.
        /// </summary>
        internal static string M0001 {
            get {
                return ResourceManager.GetString("M0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Login não cadastrado.
        /// </summary>
        internal static string M0002 {
            get {
                return ResourceManager.GetString("M0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O usuario esta inativo.
        /// </summary>
        internal static string M0003 {
            get {
                return ResourceManager.GetString("M0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O usuario esta bloqueado. Entre em contato com o administrador do sistema para executar o desbloqueio.
        /// </summary>
        internal static string M0004 {
            get {
                return ResourceManager.GetString("M0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O usuario ja efetuou um login com a senha provisoria. Favor gerar outra senha.
        /// </summary>
        internal static string M0005 {
            get {
                return ResourceManager.GetString("M0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Numero de falhas de login superior ao limite diario de falhas.
        /// </summary>
        internal static string M0006 {
            get {
                return ResourceManager.GetString("M0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Credenciais invalidas.
        /// </summary>
        internal static string M0007 {
            get {
                return ResourceManager.GetString("M0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A nova senha nao pode ser igual a anterior.
        /// </summary>
        internal static string M0008 {
            get {
                return ResourceManager.GetString("M0008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A nova senha nao foi confirmada corretamente.
        /// </summary>
        internal static string M0009 {
            get {
                return ResourceManager.GetString("M0009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Você não tem acesso a essa funcionalidade.
        /// </summary>
        internal static string M0011 {
            get {
                return ResourceManager.GetString("M0011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuário cadastrado mas sem acesso ao sistema. Consulte a administração..
        /// </summary>
        internal static string M0012 {
            get {
                return ResourceManager.GetString("M0012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nenhum registro atendeu ao filtro especificado.
        /// </summary>
        internal static string M0016 {
            get {
                return ResourceManager.GetString("M0016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nenhum arquivo selecionado.
        /// </summary>
        internal static string M0019 {
            get {
                return ResourceManager.GetString("M0019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Extensão de arquivo não suportada.
        /// </summary>
        internal static string M0020 {
            get {
                return ResourceManager.GetString("M0020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Contato já cadastrado.
        /// </summary>
        internal static string M0021 {
            get {
                return ResourceManager.GetString("M0021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome do arquivo muito longo.
        /// </summary>
        internal static string M0024 {
            get {
                return ResourceManager.GetString("M0024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Grupo já cadastrado.
        /// </summary>
        internal static string M0025 {
            get {
                return ResourceManager.GetString("M0025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O texto da mensagem deve ser preenchido.
        /// </summary>
        internal static string M0026 {
            get {
                return ResourceManager.GetString("M0026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Contato já incluído neste grupo.
        /// </summary>
        internal static string M0027 {
            get {
                return ResourceManager.GetString("M0027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Categoria de Contato já cadastrada.
        /// </summary>
        internal static string M0028 {
            get {
                return ResourceManager.GetString("M0028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não é possível excluir essa categoria. Existem informações vinculadas a ela.
        /// </summary>
        internal static string M0029 {
            get {
                return ResourceManager.GetString("M0029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Status de Contato já cadastrado.
        /// </summary>
        internal static string M0030 {
            get {
                return ResourceManager.GetString("M0030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não é possível excluir esse status de contato. Existem informações vinculadas a ele.
        /// </summary>
        internal static string M0031 {
            get {
                return ResourceManager.GetString("M0031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Padrão de Mensagem já cadastrado.
        /// </summary>
        internal static string M0032 {
            get {
                return ResourceManager.GetString("M0032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não é possível excluir esse status de contato. Existem informações vinculadas a ele.
        /// </summary>
        internal static string M0033 {
            get {
                return ResourceManager.GetString("M0033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Processo CRM criado a partir de mensagem .
        /// </summary>
        internal static string M0034 {
            get {
                return ResourceManager.GetString("M0034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Já existe um processo com o mesmo nome para este usuário.
        /// </summary>
        internal static string M0035 {
            get {
                return ResourceManager.GetString("M0035", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossível excluir esse processo. Existem ações ainda pendentes..
        /// </summary>
        internal static string M0036 {
            get {
                return ResourceManager.GetString("M0036", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A data de cancelamento não pode ser inferior a data de criação do processo.
        /// </summary>
        internal static string M0037 {
            get {
                return ResourceManager.GetString("M0037", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A data de cancelamento não pode ser superior a data corrente.
        /// </summary>
        internal static string M0038 {
            get {
                return ResourceManager.GetString("M0038", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Já existe um contato marcado como PRINCIPAL.
        /// </summary>
        internal static string M0039 {
            get {
                return ResourceManager.GetString("M0039", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossível incluir nova ação. Já existe uma ação ativa neste momento..
        /// </summary>
        internal static string M0040 {
            get {
                return ResourceManager.GetString("M0040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossível editar esta ação. Ela está encerrada ou excluída..
        /// </summary>
        internal static string M0041 {
            get {
                return ResourceManager.GetString("M0041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossível criar/reativar esta ação. Já existe uma ação ativa neste momento..
        /// </summary>
        internal static string M0042 {
            get {
                return ResourceManager.GetString("M0042", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A data de encerramento não pode ser inferior a data de criação.
        /// </summary>
        internal static string M0043 {
            get {
                return ResourceManager.GetString("M0043", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuário já cadastrado.
        /// </summary>
        internal static string M0044 {
            get {
                return ResourceManager.GetString("M0044", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não é possível excluir esse usuário. Existem informações vinculadas a ele.
        /// </summary>
        internal static string M0045 {
            get {
                return ResourceManager.GetString("M0045", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A data de encerramento não pode ser superior a data corrente.
        /// </summary>
        internal static string M0046 {
            get {
                return ResourceManager.GetString("M0046", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A data de cancelamento não pode ser inferior a data de criação.
        /// </summary>
        internal static string M0047 {
            get {
                return ResourceManager.GetString("M0047", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A data de cancelamento não pode ser superior a data corrente.
        /// </summary>
        internal static string M0048 {
            get {
                return ResourceManager.GetString("M0048", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Plano já cadastrado.
        /// </summary>
        internal static string M0049 {
            get {
                return ResourceManager.GetString("M0049", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossível excluir esse Plano. Existem assinantes vinculados a ele.
        /// </summary>
        internal static string M0050 {
            get {
                return ResourceManager.GetString("M0050", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossível incluir/reativar usuário. Número de usuários ativos excede o contratado no Plano de Assinatura.
        /// </summary>
        internal static string M0051 {
            get {
                return ResourceManager.GetString("M0051", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossível incluir/reativar contato. Número de contatos ativos excede o contratado no Plano de Assinatura.
        /// </summary>
        internal static string M0052 {
            get {
                return ResourceManager.GetString("M0052", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossível enviar este e-mail. O número de e-mails enviados na data corrente ultrapassa o contratado no Plano de Assinatura.
        /// </summary>
        internal static string M0053 {
            get {
                return ResourceManager.GetString("M0053", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossível enviar este SMS. O número de SMSs enviados na data corrente ultrapassa o contratado no Plano de Assinatura.
        /// </summary>
        internal static string M0054 {
            get {
                return ResourceManager.GetString("M0054", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossível incluir/reativar processos. Número de processos ativos excede o contratado no Plano de Assinatura.
        /// </summary>
        internal static string M0055 {
            get {
                return ResourceManager.GetString("M0055", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossível incluir/reativar ações nos processos. Número de ações ativas excede o contratado no Plano de Assinatura.
        /// </summary>
        internal static string M0056 {
            get {
                return ResourceManager.GetString("M0056", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Assinante já cadastrado.
        /// </summary>
        internal static string M0057 {
            get {
                return ResourceManager.GetString("M0057", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Filial já cadastrada.
        /// </summary>
        internal static string M0058 {
            get {
                return ResourceManager.GetString("M0058", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não é possível excluir essa Filial. Existem informações vinculadas a ela.
        /// </summary>
        internal static string M0059 {
            get {
                return ResourceManager.GetString("M0059", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Deve ser especificado um arquivo template HTML ou o corpo da mensagem.
        /// </summary>
        internal static string M0060 {
            get {
                return ResourceManager.GetString("M0060", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Corpo de mansagem especificado sem cabeçalho e área de dados (rodapé).
        /// </summary>
        internal static string M0061 {
            get {
                return ResourceManager.GetString("M0061", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nenhum filtro foi definido para montagem do grupo..
        /// </summary>
        internal static string M0062 {
            get {
                return ResourceManager.GetString("M0062", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nenhum contato obedeceu ao filtro especificado.
        /// </summary>
        internal static string M0063 {
            get {
                return ResourceManager.GetString("M0063", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Este plano de assinatura não tem acesso às funcionalidades de CRM.
        /// </summary>
        internal static string M0064 {
            get {
                return ResourceManager.GetString("M0064", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Essa mensagem/ destino já foi convertida em processo CRM.
        /// </summary>
        internal static string M0065 {
            get {
                return ResourceManager.GetString("M0065", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Categoria já cadastrada.
        /// </summary>
        internal static string M0066 {
            get {
                return ResourceManager.GetString("M0066", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cargo já cadastrado.
        /// </summary>
        internal static string M0067 {
            get {
                return ResourceManager.GetString("M0067", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossível excluir este cargo. Ele está vinculado a outras informações.
        /// </summary>
        internal static string M0068 {
            get {
                return ResourceManager.GetString("M0068", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossível excluir esta categoria. Ela está vinculada a outras informações.
        /// </summary>
        internal static string M0069 {
            get {
                return ResourceManager.GetString("M0069", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Origem do processo CRM já cadastrada.
        /// </summary>
        internal static string M0070 {
            get {
                return ResourceManager.GetString("M0070", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossível excluir esta origem. Ela está vinculada a outras informações.
        /// </summary>
        internal static string M0071 {
            get {
                return ResourceManager.GetString("M0071", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Motivo de Cancelameneto já cadastrado.
        /// </summary>
        internal static string M0072 {
            get {
                return ResourceManager.GetString("M0072", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A Senha não pode ficar em branco.
        /// </summary>
        internal static string M0073 {
            get {
                return ResourceManager.GetString("M0073", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nova senha não pode ser em branco.
        /// </summary>
        internal static string M0074 {
            get {
                return ResourceManager.GetString("M0074", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Confirmação da senha não pode ser em branco.
        /// </summary>
        internal static string M0075 {
            get {
                return ResourceManager.GetString("M0075", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossível excluir este motivo. Ele está vinculado a outras informações.
        /// </summary>
        internal static string M0076 {
            get {
                return ResourceManager.GetString("M0076", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Motivo de Encerramento já cadastrado.
        /// </summary>
        internal static string M0077 {
            get {
                return ResourceManager.GetString("M0077", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tipo de Ação já cadastrado.
        /// </summary>
        internal static string M0078 {
            get {
                return ResourceManager.GetString("M0078", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossível excluir este tipo. Ele está vinculado a outras informações.
        /// </summary>
        internal static string M0079 {
            get {
                return ResourceManager.GetString("M0079", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossível incluir/reativar cliente. Número de clientes ativos excede o contratado no Plano de Assinatura.
        /// </summary>
        internal static string M0080 {
            get {
                return ResourceManager.GetString("M0080", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossível incluir/reativar fornecedor. Número de fornecedores ativos excede o contratado no Plano de Assinatura.
        /// </summary>
        internal static string M0081 {
            get {
                return ResourceManager.GetString("M0081", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Categoria de Equipamento já cadastrada.
        /// </summary>
        internal static string M0082 {
            get {
                return ResourceManager.GetString("M0082", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Categoria de Fornecedor já cadastrada.
        /// </summary>
        internal static string M0083 {
            get {
                return ResourceManager.GetString("M0083", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O valor residual não pode ser maior que o valor de compra.
        /// </summary>
        internal static string M0084 {
            get {
                return ResourceManager.GetString("M0084", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossível incluir/reativar produto. Número de produtos ativos excede o contratado no Plano de Assinatura.
        /// </summary>
        internal static string M0085 {
            get {
                return ResourceManager.GetString("M0085", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossível excluir este produto. Ele está vinculado a outras informações.
        /// </summary>
        internal static string M0086 {
            get {
                return ResourceManager.GetString("M0086", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossível excluir este produto. Ele está vinculado a um ou mais pedidos de venda.
        /// </summary>
        internal static string M0087 {
            get {
                return ResourceManager.GetString("M0087", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Categoria de Produto já cadastrada.
        /// </summary>
        internal static string M0088 {
            get {
                return ResourceManager.GetString("M0088", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Subcategoria de Produto já cadastrada.
        /// </summary>
        internal static string M0089 {
            get {
                return ResourceManager.GetString("M0089", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossível excluir esta subcategoria. Ela está vinculada a outras informações.
        /// </summary>
        internal static string M0090 {
            get {
                return ResourceManager.GetString("M0090", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tamanho já cadastrado.
        /// </summary>
        internal static string M0091 {
            get {
                return ResourceManager.GetString("M0091", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossível excluir este tamanho. Ele está vinculado a outras informações.
        /// </summary>
        internal static string M0092 {
            get {
                return ResourceManager.GetString("M0092", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Unidade já cadastrada.
        /// </summary>
        internal static string M0093 {
            get {
                return ResourceManager.GetString("M0093", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossível excluir esta unidade. Ela está vinculada a outras informações.
        /// </summary>
        internal static string M0094 {
            get {
                return ResourceManager.GetString("M0094", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a E-Mail não cadastrado no CRMSys.
        /// </summary>
        internal static string M0096 {
            get {
                return ResourceManager.GetString("M0096", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O login não pode ficar em branco.
        /// </summary>
        internal static string M0109 {
            get {
                return ResourceManager.GetString("M0109", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a E-Mail já existente.
        /// </summary>
        internal static string M0110 {
            get {
                return ResourceManager.GetString("M0110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Login já existente.
        /// </summary>
        internal static string M0111 {
            get {
                return ResourceManager.GetString("M0111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossível incluir/reativar atendimentos. Número de atendimentos ativos excede o contratado no Plano de Assinatura.
        /// </summary>
        internal static string M0112 {
            get {
                return ResourceManager.GetString("M0112", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Definição de automação de mensagens já cadastrada.
        /// </summary>
        internal static string M0113 {
            get {
                return ResourceManager.GetString("M0113", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossível excluir este grupo. Ele está vinculaoa a outras informações.
        /// </summary>
        internal static string M0114 {
            get {
                return ResourceManager.GetString("M0114", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Grupo já cadastrado.
        /// </summary>
        internal static string M0115 {
            get {
                return ResourceManager.GetString("M0115", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossível excluir este subgrupo. Ele está vinculaoa a outras informações.
        /// </summary>
        internal static string M0116 {
            get {
                return ResourceManager.GetString("M0116", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Subgrupo já cadastrado.
        /// </summary>
        internal static string M0117 {
            get {
                return ResourceManager.GetString("M0117", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossível incluir/reativar ordens de serviço. Número de ordens de serviço ativas excede o contratado no Plano de Assinatura.
        /// </summary>
        internal static string M0118 {
            get {
                return ResourceManager.GetString("M0118", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Justificativa de cancelamento não preenchida.
        /// </summary>
        internal static string M0119 {
            get {
                return ResourceManager.GetString("M0119", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Departamento já cadastrado.
        /// </summary>
        internal static string M0120 {
            get {
                return ResourceManager.GetString("M0120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossível excluir este departamento. Ele está vinculada a outras informações.
        /// </summary>
        internal static string M0121 {
            get {
                return ResourceManager.GetString("M0121", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossível criar/reativar esta proposta. Já existe uma proposta sendo processada neste momento..
        /// </summary>
        internal static string M0122 {
            get {
                return ResourceManager.GetString("M0122", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossível editar esta proposta. Ela está encerrada, cancelada ou reprovada.
        /// </summary>
        internal static string M0123 {
            get {
                return ResourceManager.GetString("M0123", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A justificativa do cancelamento é obrigatória.
        /// </summary>
        internal static string M0124 {
            get {
                return ResourceManager.GetString("M0124", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Data de cancelamento não informada.
        /// </summary>
        internal static string M0125 {
            get {
                return ResourceManager.GetString("M0125", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A data de reprovação não pode ser inferior a data de criação do processo.
        /// </summary>
        internal static string M0126 {
            get {
                return ResourceManager.GetString("M0126", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A data de reprovação não pode ser superior a data corrente.
        /// </summary>
        internal static string M0127 {
            get {
                return ResourceManager.GetString("M0127", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A justificativa da reprovação é obrigatória.
        /// </summary>
        internal static string M0128 {
            get {
                return ResourceManager.GetString("M0128", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Data de reprovação não informada.
        /// </summary>
        internal static string M0129 {
            get {
                return ResourceManager.GetString("M0129", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A data de aprovação não pode ser inferior a data de criação do processo.
        /// </summary>
        internal static string M0130 {
            get {
                return ResourceManager.GetString("M0130", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A data de aprovação não pode ser superior a data corrente.
        /// </summary>
        internal static string M0131 {
            get {
                return ResourceManager.GetString("M0131", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A justificativa da aprovação é obrigatória.
        /// </summary>
        internal static string M0132 {
            get {
                return ResourceManager.GetString("M0132", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Data de aprovação não informada.
        /// </summary>
        internal static string M0133 {
            get {
                return ResourceManager.GetString("M0133", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Data de envio não informada.
        /// </summary>
        internal static string M0134 {
            get {
                return ResourceManager.GetString("M0134", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A data de envio não pode ser inferior a data de criação do processo.
        /// </summary>
        internal static string M0135 {
            get {
                return ResourceManager.GetString("M0135", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A data de envio não pode ser superior a data corrente.
        /// </summary>
        internal static string M0136 {
            get {
                return ResourceManager.GetString("M0136", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ocorreu erro no envio da proposta por e-mail.
        /// </summary>
        internal static string M0137 {
            get {
                return ResourceManager.GetString("M0137", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossível enviar. Nenhum arquivo anexado a essa proposta.
        /// </summary>
        internal static string M0138 {
            get {
                return ResourceManager.GetString("M0138", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nenhum template de mensagem selecionado.
        /// </summary>
        internal static string M0139 {
            get {
                return ResourceManager.GetString("M0139", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossível criar/reativar este pedido. Já existe um pedido sendo processado neste momento..
        /// </summary>
        internal static string M0140 {
            get {
                return ResourceManager.GetString("M0140", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cliente não especificado.
        /// </summary>
        internal static string M0141 {
            get {
                return ResourceManager.GetString("M0141", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tipo de ação não especificado.
        /// </summary>
        internal static string M0142 {
            get {
                return ResourceManager.GetString("M0142", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Responsável pela ação não especificado.
        /// </summary>
        internal static string M0143 {
            get {
                return ResourceManager.GetString("M0143", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Template de proposta não especificado.
        /// </summary>
        internal static string M0144 {
            get {
                return ResourceManager.GetString("M0144", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Motivo de cancelamento não especificado.
        /// </summary>
        internal static string M0145 {
            get {
                return ResourceManager.GetString("M0145", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Transportadora não especificada.
        /// </summary>
        internal static string M0146 {
            get {
                return ResourceManager.GetString("M0146", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Data prevista para entrega não especificada.
        /// </summary>
        internal static string M0147 {
            get {
                return ResourceManager.GetString("M0147", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Data de saida para entrega não especificada.
        /// </summary>
        internal static string M0148 {
            get {
                return ResourceManager.GetString("M0148", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Descrição do Motivo de cancelamento não especificada.
        /// </summary>
        internal static string M0149 {
            get {
                return ResourceManager.GetString("M0149", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Maquina de cartão já cadastrada.
        /// </summary>
        internal static string M0150 {
            get {
                return ResourceManager.GetString("M0150", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossível excluir esta máqiuna de cartão. Existem registros vinculados a ela..
        /// </summary>
        internal static string M0151 {
            get {
                return ResourceManager.GetString("M0151", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Plataforma de Entregas já cadastrada.
        /// </summary>
        internal static string M0152 {
            get {
                return ResourceManager.GetString("M0152", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossível excluir esta plataforma de entregas. Existem registros vinculados a ela..
        /// </summary>
        internal static string M0153 {
            get {
                return ResourceManager.GetString("M0153", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cargo já cadastrado.
        /// </summary>
        internal static string M0154 {
            get {
                return ResourceManager.GetString("M0154", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossível excluir este cargo. Existem registros vinculados a ele.
        /// </summary>
        internal static string M0155 {
            get {
                return ResourceManager.GetString("M0155", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pessoa Externa já cadastrada.
        /// </summary>
        internal static string M0156 {
            get {
                return ResourceManager.GetString("M0156", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossível excluir esta pessoa externa. Existem registros vinculados a ela.
        /// </summary>
        internal static string M0157 {
            get {
                return ResourceManager.GetString("M0157", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CPF já existente na lista de usuários.
        /// </summary>
        internal static string M0158 {
            get {
                return ResourceManager.GetString("M0158", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Grupo já cadastrado.
        /// </summary>
        internal static string M0159 {
            get {
                return ResourceManager.GetString("M0159", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossível excluir este grupo. Existem registros vinculados a ele..
        /// </summary>
        internal static string M0160 {
            get {
                return ResourceManager.GetString("M0160", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Subgrupo já cadastrado.
        /// </summary>
        internal static string M0161 {
            get {
                return ResourceManager.GetString("M0161", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossível excluir este subgrupo. Existem registros vinculados a ele..
        /// </summary>
        internal static string M0162 {
            get {
                return ResourceManager.GetString("M0162", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Conta já cadastrada no Plano de Contas.
        /// </summary>
        internal static string M0163 {
            get {
                return ResourceManager.GetString("M0163", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossível excluir esta conta do plano de contas. Existem registros vinculados a ela..
        /// </summary>
        internal static string M0164 {
            get {
                return ResourceManager.GetString("M0164", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Banco já cadastrado.
        /// </summary>
        internal static string M0165 {
            get {
                return ResourceManager.GetString("M0165", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossível excluir este banco. Existem registros vinculados a ele.
        /// </summary>
        internal static string M0166 {
            get {
                return ResourceManager.GetString("M0166", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Conta bancária já cadastrada.
        /// </summary>
        internal static string M0167 {
            get {
                return ResourceManager.GetString("M0167", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Já existe uma conta marcada como principal.
        /// </summary>
        internal static string M0168 {
            get {
                return ResourceManager.GetString("M0168", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nenhum lançamento cadastrado nessa conta.
        /// </summary>
        internal static string M0169 {
            get {
                return ResourceManager.GetString("M0169", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Fornecedor já cadastrado.
        /// </summary>
        internal static string M0170 {
            get {
                return ResourceManager.GetString("M0170", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossível excluir este fornecedor. Existem registros vinculados a ele.
        /// </summary>
        internal static string M0171 {
            get {
                return ResourceManager.GetString("M0171", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Forma de Pagamento/Recebimento já cadastrada.
        /// </summary>
        internal static string M0172 {
            get {
                return ResourceManager.GetString("M0172", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossível excluir esta Forma de Pagamento/Recebomento. Existem registros vinculados a ela.
        /// </summary>
        internal static string M0173 {
            get {
                return ResourceManager.GetString("M0173", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cliente já cadastrado.
        /// </summary>
        internal static string M0174 {
            get {
                return ResourceManager.GetString("M0174", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossível excluir este cliente. Existem registros vinculados a ele.
        /// </summary>
        internal static string M0175 {
            get {
                return ResourceManager.GetString("M0175", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Categoria de cliente já cadastrada.
        /// </summary>
        internal static string M0176 {
            get {
                return ResourceManager.GetString("M0176", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossível excluir esta categoria. Existem registros vinculados a ela.
        /// </summary>
        internal static string M0177 {
            get {
                return ResourceManager.GetString("M0177", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Categoria de fornecedor já cadastrada.
        /// </summary>
        internal static string M0178 {
            get {
                return ResourceManager.GetString("M0178", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossível excluir esta categoria. Existem registros vinculados a ela.
        /// </summary>
        internal static string M0179 {
            get {
                return ResourceManager.GetString("M0179", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Máquina de cartão já associada à empresa.
        /// </summary>
        internal static string M0180 {
            get {
                return ResourceManager.GetString("M0180", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Contato já cadastrado.
        /// </summary>
        internal static string M0181 {
            get {
                return ResourceManager.GetString("M0181", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossível excluir esse cliente. Exisyem processos ou propostas ativas em tramitação.
        /// </summary>
        internal static string M0182 {
            get {
                return ResourceManager.GetString("M0182", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tipo de Ação já cadastrado.
        /// </summary>
        internal static string M0183 {
            get {
                return ResourceManager.GetString("M0183", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossível excluir este tipo de ação. Existem registros vinculados a ele.
        /// </summary>
        internal static string M0184 {
            get {
                return ResourceManager.GetString("M0184", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Motivo  já cadastrado.
        /// </summary>
        internal static string M0185 {
            get {
                return ResourceManager.GetString("M0185", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossível excluir este motivo. Existem registros vinculados a ele.
        /// </summary>
        internal static string M0186 {
            get {
                return ResourceManager.GetString("M0186", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Já existe um contato marcado como principal para este processo.
        /// </summary>
        internal static string M0187 {
            get {
                return ResourceManager.GetString("M0187", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Filial já cadastrada.
        /// </summary>
        internal static string M0188 {
            get {
                return ResourceManager.GetString("M0188", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossível excluir esta filial. Existem registros vinculados a ela.
        /// </summary>
        internal static string M0189 {
            get {
                return ResourceManager.GetString("M0189", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Já existe uma filial marcada com Matriz.
        /// </summary>
        internal static string M0190 {
            get {
                return ResourceManager.GetString("M0190", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Padrão de proposta já cadastrado.
        /// </summary>
        internal static string M0191 {
            get {
                return ResourceManager.GetString("M0191", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossível excluir este padrão de proposta.  Existem registros vinculados a ele.
        /// </summary>
        internal static string M0192 {
            get {
                return ResourceManager.GetString("M0192", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Funil de processo já cadastrado.
        /// </summary>
        internal static string M0193 {
            get {
                return ResourceManager.GetString("M0193", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossível excluir este funil de processo. Existem registros vinculados a ele.
        /// </summary>
        internal static string M0194 {
            get {
                return ResourceManager.GetString("M0194", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Número de etapas excede o máximo permitido.
        /// </summary>
        internal static string M0195 {
            get {
                return ResourceManager.GetString("M0195", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ordem de processo não pode ser menor que uma já existente.
        /// </summary>
        internal static string M0196 {
            get {
                return ResourceManager.GetString("M0196", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ordem de processo não pode ser maior que o número máximo de etapas.
        /// </summary>
        internal static string M0197 {
            get {
                return ResourceManager.GetString("M0197", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Já existe uma etapa neste funil marcada como possível de encerramento.
        /// </summary>
        internal static string M0198 {
            get {
                return ResourceManager.GetString("M0198", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Já existe uma etapa neste funil marcada como etapa seguinte ao envio de proposta.
        /// </summary>
        internal static string M0199 {
            get {
                return ResourceManager.GetString("M0199", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nenhum parâmetro informado para pesquisa.
        /// </summary>
        internal static string M0200 {
            get {
                return ResourceManager.GetString("M0200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Plano de Assinatura já cadastrado.
        /// </summary>
        internal static string M0201 {
            get {
                return ResourceManager.GetString("M0201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossível excluir este funil de plano de assinatura. Existem registros vinculados a ele.
        /// </summary>
        internal static string M0202 {
            get {
                return ResourceManager.GetString("M0202", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossível uma nova ação. Número de ações ativas excede o contratado no Plano de Assinatura.
        /// </summary>
        internal static string M0203 {
            get {
                return ResourceManager.GetString("M0203", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Data de vencimento não pode ser menor que a data corrente.
        /// </summary>
        internal static string M0204 {
            get {
                return ResourceManager.GetString("M0204", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Data de pagamento não pode ser maior que a data corrente.
        /// </summary>
        internal static string M0205 {
            get {
                return ResourceManager.GetString("M0205", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Já existe um pagamento vencendo no mês informado.
        /// </summary>
        internal static string M0206 {
            get {
                return ResourceManager.GetString("M0206", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Data de início do plano não pode ser maior que a data corrente.
        /// </summary>
        internal static string M0207 {
            get {
                return ResourceManager.GetString("M0207", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Data de término do plano não pode ser menor que a data corrente.
        /// </summary>
        internal static string M0208 {
            get {
                return ResourceManager.GetString("M0208", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Data de término do plano não pode ser menor que a data inicial.
        /// </summary>
        internal static string M0209 {
            get {
                return ResourceManager.GetString("M0209", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Plano de assinatura já incluído neste assinante.
        /// </summary>
        internal static string M0210 {
            get {
                return ResourceManager.GetString("M0210", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Assinante sem nenhum plano ativo. Contrate ou reative o seuplano de assinatura.
        /// </summary>
        internal static string M0211 {
            get {
                return ResourceManager.GetString("M0211", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tipo já cadastrado.
        /// </summary>
        internal static string M0212 {
            get {
                return ResourceManager.GetString("M0212", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossível excluir este tipo. Existem registros vinculados a ele.
        /// </summary>
        internal static string M0213 {
            get {
                return ResourceManager.GetString("M0213", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Duração do plano de assinatura incompatível com sua periodicidade.
        /// </summary>
        internal static string M0214 {
            get {
                return ResourceManager.GetString("M0214", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não existe nenhum plano de assinatura ativo para esse assinante.
        /// </summary>
        internal static string M0215 {
            get {
                return ResourceManager.GetString("M0215", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Faça novamente login no CRMSys para efetivar o cancelamento do plano.
        /// </summary>
        internal static string M0216 {
            get {
                return ResourceManager.GetString("M0216", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Plano de assinatura já solicitado por este assinante.
        /// </summary>
        internal static string M0217 {
            get {
                return ResourceManager.GetString("M0217", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Padrão de e-mail já cadastrado.
        /// </summary>
        internal static string M0218 {
            get {
                return ResourceManager.GetString("M0218", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossível excluir este padrão de e-mail. Existem registros vinculados a ele.
        /// </summary>
        internal static string M0219 {
            get {
                return ResourceManager.GetString("M0219", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Padrão de SMS já cadastrado.
        /// </summary>
        internal static string M0220 {
            get {
                return ResourceManager.GetString("M0220", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossível excluir este padrão de SMS. Existem registros vinculados a ele.
        /// </summary>
        internal static string M0221 {
            get {
                return ResourceManager.GetString("M0221", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Exibindo apenas o cliente alterado. Para visualizar todos, clique em Retirar Filtro.
        /// </summary>
        internal static string M0222 {
            get {
                return ResourceManager.GetString("M0222", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A senha deve ter no mínimo o número de caracteres definido na configuração.
        /// </summary>
        internal static string M0223 {
            get {
                return ResourceManager.GetString("M0223", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A senha deve conter pelo menos uma letra maiúscula, uma minúscula e um dígito numérico.
        /// </summary>
        internal static string M0224 {
            get {
                return ResourceManager.GetString("M0224", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A senha deve conter pelo menos um  caracter especial (@#$%&amp;).
        /// </summary>
        internal static string M0225 {
            get {
                return ResourceManager.GetString("M0225", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A senha não pode conter o login nem o e-mail do usuário.
        /// </summary>
        internal static string M0226 {
            get {
                return ResourceManager.GetString("M0226", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A senha não pode ser igual à anterior.
        /// </summary>
        internal static string M0227 {
            get {
                return ResourceManager.GetString("M0227", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sua senha precisa ser redefinida. Já ultrapassou a validade definida nas configurações do sistema.
        /// </summary>
        internal static string M0228 {
            get {
                return ResourceManager.GetString("M0228", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossível agendar para data/hora anterior à data/hora corrente.
        /// </summary>
        internal static string M0229 {
            get {
                return ResourceManager.GetString("M0229", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossível incluir/reativar pesquisa. O Número de pesquisas ativas excede o contratado no Plano de Assinatura.
        /// </summary>
        internal static string M0230 {
            get {
                return ResourceManager.GetString("M0230", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pesquisa já cadastrada.
        /// </summary>
        internal static string M0231 {
            get {
                return ResourceManager.GetString("M0231", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossível excluir esta pesquisa. Existem registros vinculados a ela.
        /// </summary>
        internal static string M0232 {
            get {
                return ResourceManager.GetString("M0232", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Código de validação inválido. Tente novamente..
        /// </summary>
        internal static string M0233 {
            get {
                return ResourceManager.GetString("M0233", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Código de validação não informado..
        /// </summary>
        internal static string M0234 {
            get {
                return ResourceManager.GetString("M0234", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Uma mensagem com o código de validação foi enviada para o e-mail .
        /// </summary>
        internal static string M0235 {
            get {
                return ResourceManager.GetString("M0235", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Já existe uma categoria de ckiente com este número de ordem.
        /// </summary>
        internal static string M0236 {
            get {
                return ResourceManager.GetString("M0236", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A data devalidade não pode ser anterior à data de criação da pesquisa.
        /// </summary>
        internal static string M0237 {
            get {
                return ResourceManager.GetString("M0237", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossível excluir esta pergunta. Já existem respostas associadas a ela..
        /// </summary>
        internal static string M0238 {
            get {
                return ResourceManager.GetString("M0238", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Já existe uma pergunta com esse número de ordem.
        /// </summary>
        internal static string M0239 {
            get {
                return ResourceManager.GetString("M0239", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Envio de pesquisa sem destinatários definidos.
        /// </summary>
        internal static string M0240 {
            get {
                return ResourceManager.GetString("M0240", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Modelo de e-mail não especificado para este envio.
        /// </summary>
        internal static string M0241 {
            get {
                return ResourceManager.GetString("M0241", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cliente inválido.
        /// </summary>
        internal static string M0242 {
            get {
                return ResourceManager.GetString("M0242", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Modelo de envio pesquisa inválido.
        /// </summary>
        internal static string M0243 {
            get {
                return ResourceManager.GetString("M0243", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro na gravação de mensagem enviada.
        /// </summary>
        internal static string M0244 {
            get {
                return ResourceManager.GetString("M0244", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro na gravação do resgistro de envio.
        /// </summary>
        internal static string M0245 {
            get {
                return ResourceManager.GetString("M0245", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Grupo de clientes inválido.
        /// </summary>
        internal static string M0246 {
            get {
                return ResourceManager.GetString("M0246", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Grupo sem clientes cadastrados.
        /// </summary>
        internal static string M0247 {
            get {
                return ResourceManager.GetString("M0247", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pergunta obrigatória não pode ficar sem resposta.
        /// </summary>
        internal static string M0248 {
            get {
                return ResourceManager.GetString("M0248", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A pesquisa já foi respondida pelo usuário logado.
        /// </summary>
        internal static string M0249 {
            get {
                return ResourceManager.GetString("M0249", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Número de mensagens SMS no mês superior ao contratado no plano.
        /// </summary>
        internal static string M0250 {
            get {
                return ResourceManager.GetString("M0250", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossível o envio de mensagens SMS padrão. O número de mensagens diárias excede o contratado no Plano de Assinatura.
        /// </summary>
        internal static string M0251 {
            get {
                return ResourceManager.GetString("M0251", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossível o envio de mensagens SMS prioritárias. O número de mensagens diárias excede o contratado no Plano de Assinatura.
        /// </summary>
        internal static string M0252 {
            get {
                return ResourceManager.GetString("M0252", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O número máximo de clientes a serem importados em cada processamento é 2000. Esta planilha está excedendo esse valor..
        /// </summary>
        internal static string M0253 {
            get {
                return ResourceManager.GetString("M0253", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A imagem citada a seguir não pode ser colocada na pasta de imagens vinculadas a modelo de e-mail. Já existe imagem com mesmo nome..
        /// </summary>
        internal static string M0254 {
            get {
                return ResourceManager.GetString("M0254", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Categoria de agenda já cadastrada.
        /// </summary>
        internal static string M0255 {
            get {
                return ResourceManager.GetString("M0255", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Mensagem de E-Mail enviada com sucesso..
        /// </summary>
        internal static string M0256 {
            get {
                return ResourceManager.GetString("M0256", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Falha no envio de E-Mail..
        /// </summary>
        internal static string M0257 {
            get {
                return ResourceManager.GetString("M0257", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impissível enviar essa mensagem. Limite contratual foi atingido..
        /// </summary>
        internal static string M0258 {
            get {
                return ResourceManager.GetString("M0258", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nenhum destinatário especificado..
        /// </summary>
        internal static string M0259 {
            get {
                return ResourceManager.GetString("M0259", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossível o envio de mensagens E-Mail. O número de mensagens diárias excede o contratado no Plano de Assinatura.
        /// </summary>
        internal static string M0260 {
            get {
                return ResourceManager.GetString("M0260", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Validade do código de validação dealteração de senha expirado. Solicite uma senha provisória para entrar no CRMSys..
        /// </summary>
        internal static string M0261 {
            get {
                return ResourceManager.GetString("M0261", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuário com senha pendente de validação..
        /// </summary>
        internal static string M0262 {
            get {
                return ResourceManager.GetString("M0262", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Data/Hora de agendamento não pode ser menor do que a data/hora corrente mais 30 minutos..
        /// </summary>
        internal static string M0263 {
            get {
                return ResourceManager.GetString("M0263", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Código de validação errado..
        /// </summary>
        internal static string M0264 {
            get {
                return ResourceManager.GetString("M0264", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossível excluir esse modelo. Existem propostas ativas vinculadas a ele.
        /// </summary>
        internal static string M0265 {
            get {
                return ResourceManager.GetString("M0265", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossível excluir esse grupo. Existem mensagens ativas vinculadas a ele.
        /// </summary>
        internal static string M0266 {
            get {
                return ResourceManager.GetString("M0266", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nenhum cliente selecionado para o grupo.
        /// </summary>
        internal static string M0268 {
            get {
                return ResourceManager.GetString("M0268", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cliente não especifiado no destino.
        /// </summary>
        internal static string M0269 {
            get {
                return ResourceManager.GetString("M0269", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a TRF já incluído.
        /// </summary>
        internal static string M0270 {
            get {
                return ResourceManager.GetString("M0270", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossível excluir esse TRF. Existem registros vinculados a ele.
        /// </summary>
        internal static string M0271 {
            get {
                return ResourceManager.GetString("M0271", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Vara já cadastrada.
        /// </summary>
        internal static string M0272 {
            get {
                return ResourceManager.GetString("M0272", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossível excluir essa Vara. Existem registros vinculados a ela.
        /// </summary>
        internal static string M0273 {
            get {
                return ResourceManager.GetString("M0273", resourceCulture);
            }
        }
    }
}
