//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASSINANTE_PAGAMENTO
    {
        public int ASPA_CD_ID { get; set; }
        public int ASSI_CD_ID { get; set; }
        public Nullable<int> PLAN_CD_ID { get; set; }
        public Nullable<System.DateTime> ASPA_DT_PAGAMENTO { get; set; }
        public Nullable<decimal> ASPA_VL_VALOR { get; set; }
        public Nullable<System.DateTime> ASPA_DT_PROXIMO { get; set; }
        public Nullable<int> ASPA_IN_PAGO { get; set; }
        public Nullable<System.DateTime> ASPA_DT_VENCIMENTO { get; set; }
        public Nullable<int> ASPA_NR_ATRASO { get; set; }
        public Nullable<decimal> ASPA_VL_VALOR_PAGO { get; set; }
        public Nullable<int> ASPA_IN_ATIVO { get; set; }
    
        public virtual ASSINANTE ASSINANTE { get; set; }
        public virtual PLANO PLANO { get; set; }
    }
}
