//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BENEFICIARIO_ANEXO
    {
        public int BEAN_CD_ID { get; set; }
        public int BENE_CD_ID { get; set; }
        public string BEAN_NM_TITULO { get; set; }
        public Nullable<System.DateTime> BEAN_DT_ANEXO { get; set; }
        public Nullable<int> BEAN_IN_TIPO { get; set; }
        public string BEAN_AQ_ARQUIVO { get; set; }
        public int BEAN_IN_ATIVO { get; set; }
    
        public virtual BENEFICIARIO BENEFICIARIO { get; set; }
    }
}
