//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BENEFICIARIO_ANOTACOES
    {
        public int BECO_CD_ID { get; set; }
        public int BENE_CD_ID { get; set; }
        public Nullable<System.DateTime> BECO_DT_COMENTARIO { get; set; }
        public Nullable<int> USUA_CD_ID { get; set; }
        public string BECO_TX_TEXTO { get; set; }
        public Nullable<int> BECO_IN_ATIVO { get; set; }
    
        public virtual BENEFICIARIO BENEFICIARIO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
