//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONFIGURACAO_CHAVES
    {
        public int CFBA_CD_ID { get; set; }
        public string CONF_SG_LOGIN_SMS { get; set; }
        public string CONF_SG_SENHA_SMS { get; set; }
        public string CONF_SG_LOGIN_SMS_PRIORITARIO { get; set; }
        public string CONF_SG_SENHA_SMS_PRIORITARIO { get; set; }
        public string CONF_NM_SENDGRID_LOGIN { get; set; }
        public string CONF_NM_SENDGRID_PWD { get; set; }
        public string CONF_NM_SENDGRID_APIKEY { get; set; }
        public string CONF_CS_CONNECTION_STRING_AZURE { get; set; }
        public string CONF_NM_KEY_AZURE { get; set; }
        public string CONF_NM_ENDPOINT_AZURE { get; set; }
        public string CONF_NM_EMISSOR_AZURE { get; set; }
    }
}
