//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENDERECO
    {
        public int ENDE_CD_ID { get; set; }
        public int BENE_CD_ID { get; set; }
        public string ENDE_NM_ENDERECO { get; set; }
        public string ENDE_NM_BAIRRO { get; set; }
        public string ENDE_NM_CIDADE { get; set; }
        public int UF_CD_ID { get; set; }
        public string ENDE_NR_CEP { get; set; }
        public int ENDE_IN_ATIVO { get; set; }
    
        public virtual BENEFICIARIO BENEFICIARIO { get; set; }
        public virtual UF UF { get; set; }
    }
}
