//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HONORARIO_ANEXO
    {
        public int HOAN_CD_ID { get; set; }
        public int HONO_CD_ID { get; set; }
        public string HOAN_NM_TITULO { get; set; }
        public int HOAN_IN_TIPO { get; set; }
        public System.DateTime HOAN_DT_ANEXO { get; set; }
        public string HOAN_AQ_ARQUIVO { get; set; }
        public int HOAN_IN_ATIVO { get; set; }
    
        public virtual HONORARIO HONORARIO { get; set; }
    }
}
