//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOAS
    {
        public int LOAS_CD_ID { get; set; }
        public int PREC_CD_ID { get; set; }
        public int TRF1_CD_ID { get; set; }
        public Nullable<int> NATU_CD_ID { get; set; }
        public string LOAS_NR_ANO { get; set; }
        public string LOAS_NM_UO_CADASTRADA { get; set; }
        public string LOAS_NM_UO_DEVEDORA { get; set; }
        public string LOAS_NM_TIPO_CAUSA { get; set; }
        public decimal LOAS_VL_VALOR { get; set; }
        public int LOAS_IN_ATIVO { get; set; }
    
        public virtual NATUREZA NATUREZA { get; set; }
        public virtual PRECATORIO PRECATORIO { get; set; }
        public virtual TRF TRF { get; set; }
    }
}
