//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PACIENTE_ANAMNESE
    {
        public int PAAM_CD_ID { get; set; }
        public int PACI_CD_ID { get; set; }
        public System.DateTime PAAM_DT_DATA { get; set; }
        public string PAAN_NR_PA { get; set; }
        public string PAAN_NR_PESO { get; set; }
        public Nullable<decimal> PAAM_NR_PESO_KG { get; set; }
        public Nullable<decimal> PAAM_NR_ALTURA { get; set; }
        public string PAAN_NM_ACV { get; set; }
        public string PAAN_NM_AR { get; set; }
        public string PAAN_NM_ABDOMEM { get; set; }
        public string PAAN_NM_MMII { get; set; }
        public string PAAM_DS_QP { get; set; }
        public string PAAM_DS_HDA { get; set; }
        public string PAAM_DS_HPP { get; set; }
        public string PAAM_DS_HFAM { get; set; }
        public string PAAM_DS_HSOCIAL { get; set; }
        public string PAAM_DS_EXAME_FISICO { get; set; }
        public string PAAM_DS_DIAGNOSTICO_1 { get; set; }
        public string PAAM_DS_DIAGNOSTICO_2 { get; set; }
        public string PAAM_TX_EXAMES { get; set; }
        public string PAAM_TX_TEXTO { get; set; }
        public int PAAM_IN_ATIVO { get; set; }
    
        public virtual PACIENTE PACIENTE { get; set; }
    }
}
