//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PACIENTE_PRESCRICAO
    {
        public int PAPR_CD_ID { get; set; }
        public int PACI_CD_ID { get; set; }
        public int PAPR_IN_TIPO { get; set; }
        public System.DateTime PAPR_DT_DATA { get; set; }
        public string PAPR_NM_REMEDIO { get; set; }
        public string PAPR_NM_DOSAGEM { get; set; }
        public string PAPR_NM_FORMA { get; set; }
        public string PAPR_NM_POSOLOGIA { get; set; }
        public int PAPR_IN_ATIVO { get; set; }
    
        public virtual PACIENTE PACIENTE { get; set; }
    }
}
