//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRECATORIO_FALHA
    {
        public int PRFA_CD_ID { get; set; }
        public string PRFA_NM_TRF { get; set; }
        public string PRFA_NM_PRECATORIO { get; set; }
        public Nullable<System.DateTime> PRFA_DT_DATA { get; set; }
        public string PRFA_DS_MOTIVO { get; set; }
    }
}
