//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECURSIVIDADE_DESTINO
    {
        public int REDE_CD_ID { get; set; }
        public int RECU_CD_ID { get; set; }
        public int CLIE_CD_ID { get; set; }
        public string REDE_NR_CELULAR { get; set; }
        public string REDE_EM_EMAIL { get; set; }
        public string REDE_NM_NOME { get; set; }
        public string REDE_TX_CORPO { get; set; }
        public int REDE_IN_ATIVO { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual RECURSIVIDADE RECURSIVIDADE { get; set; }
    }
}
