//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RidolfiDB_WebEntities : DbContext
    {
        public RidolfiDB_WebEntities()
            : base("name=RidolfiDB_WebEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AGENDA> AGENDA { get; set; }
        public virtual DbSet<AGENDA_ANEXO> AGENDA_ANEXO { get; set; }
        public virtual DbSet<AGENDA_VINCULO> AGENDA_VINCULO { get; set; }
        public virtual DbSet<ASSINANTE> ASSINANTE { get; set; }
        public virtual DbSet<ASSINANTE_ANEXO> ASSINANTE_ANEXO { get; set; }
        public virtual DbSet<ASSINANTE_ANOTACAO> ASSINANTE_ANOTACAO { get; set; }
        public virtual DbSet<ASSINANTE_CONSUMO> ASSINANTE_CONSUMO { get; set; }
        public virtual DbSet<ASSINANTE_PAGAMENTO> ASSINANTE_PAGAMENTO { get; set; }
        public virtual DbSet<ASSINANTE_PLANO> ASSINANTE_PLANO { get; set; }
        public virtual DbSet<ASSINANTE_QUADRO_SOCIETARIO> ASSINANTE_QUADRO_SOCIETARIO { get; set; }
        public virtual DbSet<BANCO> BANCO { get; set; }
        public virtual DbSet<BENEFICIARIO> BENEFICIARIO { get; set; }
        public virtual DbSet<BENEFICIARIO_ANEXO> BENEFICIARIO_ANEXO { get; set; }
        public virtual DbSet<BENEFICIARIO_ANOTACOES> BENEFICIARIO_ANOTACOES { get; set; }
        public virtual DbSet<CARGO> CARGO { get; set; }
        public virtual DbSet<CATEGORIA_AGENDA> CATEGORIA_AGENDA { get; set; }
        public virtual DbSet<CATEGORIA_CLIENTE> CATEGORIA_CLIENTE { get; set; }
        public virtual DbSet<CATEGORIA_NOTIFICACAO> CATEGORIA_NOTIFICACAO { get; set; }
        public virtual DbSet<CATEGORIA_TELEFONE> CATEGORIA_TELEFONE { get; set; }
        public virtual DbSet<CATEGORIA_USUARIO> CATEGORIA_USUARIO { get; set; }
        public virtual DbSet<CLIENTE> CLIENTE { get; set; }
        public virtual DbSet<CLIENTE_ANEXO> CLIENTE_ANEXO { get; set; }
        public virtual DbSet<CLIENTE_ANOTACAO> CLIENTE_ANOTACAO { get; set; }
        public virtual DbSet<CLIENTE_CONTATO> CLIENTE_CONTATO { get; set; }
        public virtual DbSet<CLIENTE_FALHA> CLIENTE_FALHA { get; set; }
        public virtual DbSet<CLIENTE_QUADRO_SOCIETARIO> CLIENTE_QUADRO_SOCIETARIO { get; set; }
        public virtual DbSet<CLIENTE_REFERENCIA> CLIENTE_REFERENCIA { get; set; }
        public virtual DbSet<CLIENTE_TAG> CLIENTE_TAG { get; set; }
        public virtual DbSet<CONFIGURACAO> CONFIGURACAO { get; set; }
        public virtual DbSet<CONFIGURACAO_CHAVES> CONFIGURACAO_CHAVES { get; set; }
        public virtual DbSet<CONFIGURACAO_CRIPT> CONFIGURACAO_CRIPT { get; set; }
        public virtual DbSet<CONTATO> CONTATO { get; set; }
        public virtual DbSet<CONTATO_FALHA> CONTATO_FALHA { get; set; }
        public virtual DbSet<CRM> CRM { get; set; }
        public virtual DbSet<CRM_ACAO> CRM_ACAO { get; set; }
        public virtual DbSet<CRM_ANEXO> CRM_ANEXO { get; set; }
        public virtual DbSet<CRM_COMENTARIO> CRM_COMENTARIO { get; set; }
        public virtual DbSet<CRM_CONTATO> CRM_CONTATO { get; set; }
        public virtual DbSet<CRM_FOLLOW> CRM_FOLLOW { get; set; }
        public virtual DbSet<CRM_ORIGEM> CRM_ORIGEM { get; set; }
        public virtual DbSet<CRM_PEDIDO_VENDA> CRM_PEDIDO_VENDA { get; set; }
        public virtual DbSet<CRM_PEDIDO_VENDA_ACOMPANHAMENTO> CRM_PEDIDO_VENDA_ACOMPANHAMENTO { get; set; }
        public virtual DbSet<CRM_PEDIDO_VENDA_ANEXO> CRM_PEDIDO_VENDA_ANEXO { get; set; }
        public virtual DbSet<DEPARTAMENTO> DEPARTAMENTO { get; set; }
        public virtual DbSet<DIARIO_PROCESSO> DIARIO_PROCESSO { get; set; }
        public virtual DbSet<EMAIL_AGENDAMENTO> EMAIL_AGENDAMENTO { get; set; }
        public virtual DbSet<ENDERECO> ENDERECO { get; set; }
        public virtual DbSet<ESCOLARIDADE> ESCOLARIDADE { get; set; }
        public virtual DbSet<ESTADO_CIVIL> ESTADO_CIVIL { get; set; }
        public virtual DbSet<FUNIL> FUNIL { get; set; }
        public virtual DbSet<FUNIL_ETAPA> FUNIL_ETAPA { get; set; }
        public virtual DbSet<GRAU_INSTRUCAO> GRAU_INSTRUCAO { get; set; }
        public virtual DbSet<GRUPO> GRUPO { get; set; }
        public virtual DbSet<GRUPO_CLIENTE> GRUPO_CLIENTE { get; set; }
        public virtual DbSet<HONORARIO> HONORARIO { get; set; }
        public virtual DbSet<HONORARIO_ANEXO> HONORARIO_ANEXO { get; set; }
        public virtual DbSet<HONORARIO_ANOTACOES> HONORARIO_ANOTACOES { get; set; }
        public virtual DbSet<LINGUA> LINGUA { get; set; }
        public virtual DbSet<LOAS> LOAS { get; set; }
        public virtual DbSet<LOG> LOG { get; set; }
        public virtual DbSet<LOG_EXCECAO> LOG_EXCECAO { get; set; }
        public virtual DbSet<LOG_EXCECAO_NOVO> LOG_EXCECAO_NOVO { get; set; }
        public virtual DbSet<MENSAGEM_ANEXO> MENSAGEM_ANEXO { get; set; }
        public virtual DbSet<MENSAGEM_AUTOMACAO> MENSAGEM_AUTOMACAO { get; set; }
        public virtual DbSet<MENSAGEM_AUTOMACAO_DATAS> MENSAGEM_AUTOMACAO_DATAS { get; set; }
        public virtual DbSet<MENSAGENS> MENSAGENS { get; set; }
        public virtual DbSet<MENSAGENS_DESTINOS> MENSAGENS_DESTINOS { get; set; }
        public virtual DbSet<MENSAGENS_ENVIADAS_SISTEMA> MENSAGENS_ENVIADAS_SISTEMA { get; set; }
        public virtual DbSet<MOTIVO_CANCELAMENTO> MOTIVO_CANCELAMENTO { get; set; }
        public virtual DbSet<MOTIVO_ENCERRAMENTO> MOTIVO_ENCERRAMENTO { get; set; }
        public virtual DbSet<MUNICIPIO> MUNICIPIO { get; set; }
        public virtual DbSet<NACIONALIDADE> NACIONALIDADE { get; set; }
        public virtual DbSet<NATUREZA> NATUREZA { get; set; }
        public virtual DbSet<NOMENCLATURA_BRAS_SERVICOS> NOMENCLATURA_BRAS_SERVICOS { get; set; }
        public virtual DbSet<NOTICIA> NOTICIA { get; set; }
        public virtual DbSet<NOTICIA_COMENTARIO> NOTICIA_COMENTARIO { get; set; }
        public virtual DbSet<NOTIFICACAO> NOTIFICACAO { get; set; }
        public virtual DbSet<NOTIFICACAO_ANEXO> NOTIFICACAO_ANEXO { get; set; }
        public virtual DbSet<PARENTESCO> PARENTESCO { get; set; }
        public virtual DbSet<PERFIL> PERFIL { get; set; }
        public virtual DbSet<PERIODICIDADE> PERIODICIDADE { get; set; }
        public virtual DbSet<PERIODICIDADE_TAREFA> PERIODICIDADE_TAREFA { get; set; }
        public virtual DbSet<PLANO> PLANO { get; set; }
        public virtual DbSet<PLANO_PERIODICIDADE> PLANO_PERIODICIDADE { get; set; }
        public virtual DbSet<PRECATORIO> PRECATORIO { get; set; }
        public virtual DbSet<PRECATORIO_ANEXO> PRECATORIO_ANEXO { get; set; }
        public virtual DbSet<PRECATORIO_ANOTACAO> PRECATORIO_ANOTACAO { get; set; }
        public virtual DbSet<PRECATORIO_ESTADO> PRECATORIO_ESTADO { get; set; }
        public virtual DbSet<PRECATORIO_FALHA> PRECATORIO_FALHA { get; set; }
        public virtual DbSet<QUALIFICACAO> QUALIFICACAO { get; set; }
        public virtual DbSet<QUEM_DESLIGOU> QUEM_DESLIGOU { get; set; }
        public virtual DbSet<RECURSIVIDADE> RECURSIVIDADE { get; set; }
        public virtual DbSet<RECURSIVIDADE_DATA> RECURSIVIDADE_DATA { get; set; }
        public virtual DbSet<RECURSIVIDADE_DESTINO> RECURSIVIDADE_DESTINO { get; set; }
        public virtual DbSet<REGIME_TRIBUTARIO> REGIME_TRIBUTARIO { get; set; }
        public virtual DbSet<RESULTADO_ROBOT> RESULTADO_ROBOT { get; set; }
        public virtual DbSet<SEXO> SEXO { get; set; }
        public virtual DbSet<TABELA_IMPORTACAO> TABELA_IMPORTACAO { get; set; }
        public virtual DbSet<TABELA_IPCA> TABELA_IPCA { get; set; }
        public virtual DbSet<TABELA_IRRF> TABELA_IRRF { get; set; }
        public virtual DbSet<TAREFA> TAREFA { get; set; }
        public virtual DbSet<TAREFA_ACOMPANHAMENTO> TAREFA_ACOMPANHAMENTO { get; set; }
        public virtual DbSet<TAREFA_ANEXO> TAREFA_ANEXO { get; set; }
        public virtual DbSet<TAREFA_NOTIFICACAO> TAREFA_NOTIFICACAO { get; set; }
        public virtual DbSet<TAREFA_VINCULO> TAREFA_VINCULO { get; set; }
        public virtual DbSet<TELEFONE> TELEFONE { get; set; }
        public virtual DbSet<TEMPLATE> TEMPLATE { get; set; }
        public virtual DbSet<TEMPLATE_EMAIL> TEMPLATE_EMAIL { get; set; }
        public virtual DbSet<TEMPLATE_PROPOSTA> TEMPLATE_PROPOSTA { get; set; }
        public virtual DbSet<TEMPLATE_SMS> TEMPLATE_SMS { get; set; }
        public virtual DbSet<TIPO_ACAO> TIPO_ACAO { get; set; }
        public virtual DbSet<TIPO_CONTRIBUINTE> TIPO_CONTRIBUINTE { get; set; }
        public virtual DbSet<TIPO_CRM> TIPO_CRM { get; set; }
        public virtual DbSet<TIPO_FOLLOW> TIPO_FOLLOW { get; set; }
        public virtual DbSet<TIPO_GRUPO> TIPO_GRUPO { get; set; }
        public virtual DbSet<TIPO_PESSOA> TIPO_PESSOA { get; set; }
        public virtual DbSet<TIPO_TAREFA> TIPO_TAREFA { get; set; }
        public virtual DbSet<TIPO_TELEFONE> TIPO_TELEFONE { get; set; }
        public virtual DbSet<TIPO_TELEFONE_BASE> TIPO_TELEFONE_BASE { get; set; }
        public virtual DbSet<TITULARIDADE> TITULARIDADE { get; set; }
        public virtual DbSet<TRF> TRF { get; set; }
        public virtual DbSet<UF> UF { get; set; }
        public virtual DbSet<USUARIO> USUARIO { get; set; }
        public virtual DbSet<USUARIO_ANEXO> USUARIO_ANEXO { get; set; }
        public virtual DbSet<USUARIO_ANOTACAO> USUARIO_ANOTACAO { get; set; }
        public virtual DbSet<VARA> VARA { get; set; }
        public virtual DbSet<VIDEO> VIDEO { get; set; }
        public virtual DbSet<VIDEO_COMENTARIO> VIDEO_COMENTARIO { get; set; }
        public virtual DbSet<VOLTA_PESQUISA> VOLTA_PESQUISA { get; set; }
    }
}
