//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TABELA_IRRF
    {
        public int IRRF_CD_ID { get; set; }
        public int IRRF_IN_FAIXA { get; set; }
        public decimal IRRF_VL_ALIQUOTA { get; set; }
        public decimal IRRF_VL_PORCENTAGEM { get; set; }
        public decimal IRRF_VL_VALOR { get; set; }
        public int IRRF_IN_ATIVO { get; set; }
    }
}
