//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TABELA_IMPORTACAO
    {
        public int TAIM_CD_ID { get; set; }
        public string TAIM_SG_TRF { get; set; }
        public Nullable<System.DateTime> TAIM_DT_DATA { get; set; }
        public string TAIM_NM_PRECATORIO { get; set; }
        public string TAIM_DS_MENSAGEM { get; set; }
        public int TAIM_IN_ATIVO { get; set; }
    }
}
